services:
  app:
    build: .
    container_name: mye-r
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - POSTGRES_HOST=db # This should always be the service name
      - POSTGRES_PORT=5432 # This is the port INSIDE the db container
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mye_r
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mye_r?sslmode=disable # Same here
    volumes:
      - /data/myerdata:/myer/data
      - /media/myer/library:/app/library
      - /media/debridmedia/__all__:/app/rclone
      - /data/myerdata/.env:/app/.env
      - /data/myerdata/config.yaml:/app/config.yaml
    networks:
      - myer-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  db:
    image: postgres:16-alpine
    container_name: myer-db
    restart: unless-stopped
    ports:
      - "5433:5432" # Host port:Container port
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mye_r
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mye_r"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  myer-network:
    driver: bridge

volumes:
  postgres_data: