services:
  app:
    build: .
    container_name: mye-r
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mye_r
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mye_r?sslmode=disable
    volumes:
      - /data/myerdata:/myer/data
      - /media/myer/library:/app/library
      - /media/debridmedia/__all__:/app/rclone
      - /data/myerdata/.env:/app/.env
      - /data/myerdata/config.yaml:/app/config.yaml
    networks:
      - myer-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  db:
    image: postgres:16-alpine
    container_name: myer-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mye_r
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  myer-network:
    driver: bridge

volumes:
  postgres_data:
